export const SET_SEAPORTID = 'SET_SEAPORTID';
export const SET_GOODS_INTEGRAL_ID = 'SET_GOODS_INTEGRAL_ID';
export const SET_ORDER_ID = 'SET_ORDER_ID';
export const SET_SETTLEMENTS_ID = 'SET_SETTLEMENTS_ID';
export const SET_PERMISSIONS = 'SET_PERMISSIONS';
export const SET_COMMISSION_NAME = 'SET_COMMISSION_NAME';
export const SET_MEMBER_ID = 'SET_MEMBER_ID';
