###设置服务器启动Ip
server:
  port: 10010
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/xml,application/javascript,text/html,text/xml,text/plain,text/css
  tomcat:
    max-http-post-size: 20971520
  token:
    time: 86400
spring:
  profiles:
    active: dev
  freemarker:
    allow-request-override: true
    allow-session-override: true
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html;
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    template-loader-path: classpath:/templates/,classpath:/static/,classpath:/public/
    prefix: classpath:/templates/
    suffix: .html
    request-context-attribute: request
    settings:
      template_update_delay: 0
      url_escaping_charset: UTF-8
      locale: UTF-8
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      template_exception_handler: html_debug
      # 数字格式化，无小数点
      number_format: '0.#'
      # 设置freemarker标签 0,1,2 0=自动识别，默认1
      tag_syntax: 'auto_detect'
mybatis:
  type-aliases-package: com.xgb.model
  config-location: classpath:mybatis-com.xgb.config.xml
logging:
  level:
    root: info
    level.com.hatchet: trace
    path: xgb-lovexgb/lovexgb-admin/logs/boot-api.log
