package com.xgb.service;

import com.xgb.common.Utils;
import com.xgb.model.StNjInner4;
import com.xgb.util.DateUtils;
import com.xgb.util.MyTools;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
* @Auther: 
* @Date: 2019年12月25日 12:08:46
* @Description:
*/
public class ReadStNjInner4Service {

    public static StNjInner4 getContent(){
        List<StNjInner4> lists = new ArrayList<StNjInner4>();
        String path = Utils.getResourceBasePath() + "/xgb-data/data-api/config/StNjInner4.txt";
        File file = new File(path);
        StNjInner4  entity = null;
        Boolean boo = file.exists() && file.isFile();
        if(boo){
            BufferedReader bufferedReader = null;
            try {
                //构造一个BufferedReader类来读取文件
                bufferedReader = new BufferedReader(new FileReader(file));
                String linetxt = null;
                //result用来存储文件内容
                StringBuilder result = new StringBuilder();
                //按使用readLine方法，一次读一行
                while ((linetxt = bufferedReader.readLine()) != null) {
                    result.append(linetxt);
                }
                //输出读出的所有数据（StringBuilder类型）
                entity = getEntity(result.toString());
                lists.add(entity);
            } catch (Exception e) {
                System.out.println("读取文件内容出错");
                e.printStackTrace();
            } finally {
                try {
                    bufferedReader.close();
                } catch (IOException e1) {
                    e1.printStackTrace();
                }
            }
        }
        return entity;
    }
    public static StNjInner4 getEntity(String result){
        String[] split = result.split("\\|");
        StNjInner4 fcc = new StNjInner4();
        if(MyTools.isNotEmpty(split[0])){
            fcc.setId(Integer.parseInt(split[0]));
        }
        if(MyTools.isNotEmpty(split[1])){
            fcc.setInstanceid(split[1]);
        }
        if(MyTools.isNotEmpty(split[2])){
            fcc.setOrganizationid(split[2]);
        }
        if(MyTools.isNotEmpty(split[3])){
            fcc.setStatus(Integer.parseInt(split[3]));
        }
        if(MyTools.isNotEmpty(split[4])){
            fcc.setBiangengmingcheng(split[4]);
        }
        if(MyTools.isNotEmpty(split[5])){
            fcc.setBiangengmingchengbanli(split[5]);
        }
        if(MyTools.isNotEmpty(split[6])){
            fcc.setBiangengmingchengshijian(DateUtils.strToDateLong(split[6]));
        }
        if(MyTools.isNotEmpty(split[7])){
            fcc.setBiangengdiyu(split[7]);
        }
        if(MyTools.isNotEmpty(split[8])){
            fcc.setBiangengdiyubanli(split[8]);
        }
        if(MyTools.isNotEmpty(split[9])){
            fcc.setBiangengdiyushijian(DateUtils.strToDateLong(split[9]));
        }
        if(MyTools.isNotEmpty(split[10])){
            fcc.setBiangengyewu(split[10]);
        }
        if(MyTools.isNotEmpty(split[11])){
            fcc.setBiangengyewubanli(split[11]);
        }
        if(MyTools.isNotEmpty(split[12])){
            fcc.setBiangengyewushijian(DateUtils.strToDateLong(split[12]));
        }
        if(MyTools.isNotEmpty(split[13])){
            fcc.setBiangengzhusuo(split[13]);
        }
        if(MyTools.isNotEmpty(split[14])){
            fcc.setBiangengzhusuobanli(split[14]);
        }
        if(MyTools.isNotEmpty(split[15])){
            fcc.setBiangengzhusuoshijian(DateUtils.strToDateLong(split[15]));
        }
        if(MyTools.isNotEmpty(split[16])){
            fcc.setBiangengzijin(split[16]);
        }
        if(MyTools.isNotEmpty(split[17])){
            fcc.setBiangengzijinbanli(split[17]);
        }
        if(MyTools.isNotEmpty(split[18])){
            fcc.setBiangengzijinshijian(DateUtils.strToDateLong(split[18]));
        }
        if(MyTools.isNotEmpty(split[19])){
            fcc.setBiangengfaren(split[19]);
        }
        if(MyTools.isNotEmpty(split[20])){
            fcc.setBiangengfarenbanli(split[20]);
        }
        if(MyTools.isNotEmpty(split[21])){
            fcc.setBiangengfarenshijian(DateUtils.strToDateLong(split[21]));
        }
        if(MyTools.isNotEmpty(split[22])){
            fcc.setBiangengzhuguandanwei(split[22]);
        }
        if(MyTools.isNotEmpty(split[23])){
            fcc.setBianzhuguandanweibanli(split[23]);
        }
        if(MyTools.isNotEmpty(split[24])){
            fcc.setBianzhuguandanweishijian(DateUtils.strToDateLong(split[24]));
        }
        if(MyTools.isNotEmpty(split[25])){
            fcc.setXiugaizhangcheng(split[25]);
        }
        if(MyTools.isNotEmpty(split[26])){
            fcc.setXiugaizhangchengbanli(split[26]);
        }
        if(MyTools.isNotEmpty(split[27])){
            fcc.setXiugaizhangchengshijian(DateUtils.strToDateLong(split[27]));
        }
        if(MyTools.isNotEmpty(split[28])){
            fcc.setFuzerenbiangeng(split[28]);
        }
        if(MyTools.isNotEmpty(split[29])){
            fcc.setFuzerenbiangengbanli(split[29]);
        }
        if(MyTools.isNotEmpty(split[30])){
            fcc.setFuzerenbianshijian(DateUtils.strToDateLong(split[30]));
        }
        if(MyTools.isNotEmpty(split[31])){
            fcc.setHuiyuandahuinianjie(Integer.parseInt(split[31]));
        }
        if(MyTools.isNotEmpty(split[32])){
            fcc.setHuanjiedahuishijian(DateUtils.strToDateLong(split[32]));
        }
        if(MyTools.isNotEmpty(split[33])){
            fcc.setHuiyuandahuinianci(Integer.parseInt(split[33]));
        }
        if(MyTools.isNotEmpty(split[34])){
            fcc.setHuiyuandahuishijian(DateUtils.strToDateLong(split[34]));
        }
        if(MyTools.isNotEmpty(split[35])){
            fcc.setLishihuinian(split[35]);
        }
        if(MyTools.isNotEmpty(split[36])){
            fcc.setLishihuici(Integer.parseInt(split[36]));
        }
        if(MyTools.isNotEmpty(split[37])){
            fcc.setLishihuibennianci(Integer.parseInt(split[37]));
        }
        if(MyTools.isNotEmpty(split[38])){
            fcc.setChanglishihuinian(split[38]);
        }
        if(MyTools.isNotEmpty(split[39])){
            fcc.setChanglishihuici(Integer.parseInt(split[39]));
        }
        if(MyTools.isNotEmpty(split[40])){
            fcc.setChanglishihuibennianci(Integer.parseInt(split[40]));
        }
        if(MyTools.isNotEmpty(split[41])){
            fcc.setJigouzhidu(split[41]);
        }
        if(MyTools.isNotEmpty(split[42])){
            fcc.setZhengshuzhidu(split[42]);
        }
        if(MyTools.isNotEmpty(split[43])){
            fcc.setYinzhangzhidu(split[43]);
        }
        if(MyTools.isNotEmpty(split[44])){
            fcc.setRenshizhidu(split[44]);
        }
        if(MyTools.isNotEmpty(split[45])){
            fcc.setHetongrenshu(Integer.parseInt(split[45]));
        }
        if(MyTools.isNotEmpty(split[46])){
            fcc.setShiyebaoxian(Integer.parseInt(split[46]));
        }
        if(MyTools.isNotEmpty(split[47])){
            fcc.setYanglaobaoxian(Integer.parseInt(split[47]));
        }
        if(MyTools.isNotEmpty(split[48])){
            fcc.setYiliaobaoxian(Integer.parseInt(split[48]));
        }
        if(MyTools.isNotEmpty(split[49])){
            fcc.setGongshangbaoxian(Integer.parseInt(split[49]));
        }
        if(MyTools.isNotEmpty(split[50])){
            fcc.setShengyubaoxian(Integer.parseInt(split[50]));
        }
        if(MyTools.isNotEmpty(split[51])){
            fcc.setKaihuyinxing(split[51]);
        }
        if(MyTools.isNotEmpty(split[52])){
            fcc.setYinxingzhanghao(split[52]);
        }
        if(MyTools.isNotEmpty(split[53])){
            fcc.setWaibikaihuyinxing(split[53]);
        }
        if(MyTools.isNotEmpty(split[54])){
            fcc.setWaibiyinxingzhanghao(split[54]);
        }
        if(MyTools.isNotEmpty(split[55])){
            fcc.setCaizhengdengji(split[55]);
        }
        if(MyTools.isNotEmpty(split[56])){
            fcc.setCaihuirenyuanshu(Integer.parseInt(split[56]));
        }
        if(MyTools.isNotEmpty(split[57])){
            fcc.setZhiyezigerenshu(Integer.parseInt(split[57]));
        }
        if(MyTools.isNotEmpty(split[58])){
            fcc.setPiaojuzhongleiqita(split[58]);
        }
        if(MyTools.isNotEmpty(split[59])){
            fcc.setCaiwuruanjian(split[59]);
        }
        if(MyTools.isNotEmpty(split[60])){
            fcc.setZhengshubaoguandi(split[60]);
        }
        if(MyTools.isNotEmpty(split[61])){
            fcc.setYinzhangbaoguandi(split[61]);
        }
        if(MyTools.isNotEmpty(split[62])){
            fcc.setGuoshui(split[62]);
        }
        if(MyTools.isNotEmpty(split[63])){
            fcc.setDishui(split[63]);
        }
        if(MyTools.isNotEmpty(split[64])){
            fcc.setWeidengji(split[64]);
        }
        if(MyTools.isNotEmpty(split[65])){
            fcc.setYinqianshouju(split[65]);
        }
        if(MyTools.isNotEmpty(split[66])){
            fcc.setHuifeishouju(split[66]);
        }
        if(MyTools.isNotEmpty(split[67])){
            fcc.setJuanzengshouju(split[67]);
        }
        if(MyTools.isNotEmpty(split[68])){
            fcc.setShuiwufapiao(split[68]);
        }
        if(MyTools.isNotEmpty(split[69])){
            fcc.setQitapiaoju(split[69]);
        }
        if(MyTools.isNotEmpty(split[70])){
            fcc.setNiandu(split[70]);
        }
        if(MyTools.isNotEmpty(split[71])){
            fcc.setBgzongzhi(split[71]);
        }
        if(MyTools.isNotEmpty(split[72])){
            fcc.setBgzongzhibanli(split[72]);
        }
        if(MyTools.isNotEmpty(split[73])){
            fcc.setBgzongzhishijian(DateUtils.strToDateLong(split[73]));
        }
        if(MyTools.isNotEmpty(split[74])){
            fcc.setBgfenzhimingcheng(split[74]);
        }
        if(MyTools.isNotEmpty(split[75])){
            fcc.setBgfenzhimingchengbanli(split[75]);
        }
        if(MyTools.isNotEmpty(split[76])){
            fcc.setBgfenzhimingchengshijian(DateUtils.strToDateLong(split[76]));
        }
        if(MyTools.isNotEmpty(split[77])){
            fcc.setBgfenzhiyewufanwei(split[77]);
        }
        if(MyTools.isNotEmpty(split[78])){
            fcc.setBgfenzhiyewubanli(split[78]);
        }
        if(MyTools.isNotEmpty(split[79])){
            fcc.setBgfenzhiyewushijian(DateUtils.strToDateLong(split[79]));
        }
        if(MyTools.isNotEmpty(split[80])){
            fcc.setBgfenzhifuzeren(split[80]);
        }
        if(MyTools.isNotEmpty(split[81])){
            fcc.setBgfenzhifuzerenbanli(split[81]);
        }
        if(MyTools.isNotEmpty(split[82])){
            fcc.setBgfenzhifuzerenshijian(DateUtils.strToDateLong(split[82]));
        }
        if(MyTools.isNotEmpty(split[83])){
            fcc.setBgfenzhizhusuo(split[83]);
        }
        if(MyTools.isNotEmpty(split[84])){
            fcc.setBgfenzhizhusuobanli(split[84]);
        }
        if(MyTools.isNotEmpty(split[85])){
            fcc.setBgfenzhizhusuoshijian(DateUtils.strToDateLong(split[85]));
        }
        if(MyTools.isNotEmpty(split[86])){
            fcc.setXingmingyi(split[86]);
        }
        if(MyTools.isNotEmpty(split[87])){
            fcc.setGangweiyi(split[87]);
        }
        if(MyTools.isNotEmpty(split[88])){
            fcc.setKuaijizhengyi(split[88]);
        }
        if(MyTools.isNotEmpty(split[89])){
            fcc.setJishuzigeyi(split[89]);
        }
        if(MyTools.isNotEmpty(split[90])){
            fcc.setXingminger(split[90]);
        }
        if(MyTools.isNotEmpty(split[91])){
            fcc.setGangweier(split[91]);
        }
        if(MyTools.isNotEmpty(split[92])){
            fcc.setKuaijizhenger(split[92]);
        }
        if(MyTools.isNotEmpty(split[93])){
            fcc.setJishuzigeer(split[93]);
        }
        if(MyTools.isNotEmpty(split[94])){
            fcc.setXingmingsan(split[94]);
        }
        if(MyTools.isNotEmpty(split[95])){
            fcc.setGangweisan(split[95]);
        }
        if(MyTools.isNotEmpty(split[96])){
            fcc.setKuaijizhengsan(split[96]);
        }
        if(MyTools.isNotEmpty(split[97])){
            fcc.setJishuzigesan(split[97]);
        }
        if(MyTools.isNotEmpty(split[98])){
            fcc.setXingmingsi(split[98]);
        }
        if(MyTools.isNotEmpty(split[99])){
            fcc.setGangweisi(split[99]);
        }
        if(MyTools.isNotEmpty(split[100])){
            fcc.setKuaijizhengsi(split[100]);
        }
        if(MyTools.isNotEmpty(split[101])){
            fcc.setJishuzigesi(split[101]);
        }
        if(MyTools.isNotEmpty(split[102])){
            fcc.setGongjijin(Integer.parseInt(split[102]));
        }
        if(MyTools.isNotEmpty(split[103])){
            fcc.setZhuanzhigongzi(Integer.parseInt(split[103]));
        }
        if(MyTools.isNotEmpty(split[104])){
            fcc.setZhaokaishijian(split[104]);
        }
        if(MyTools.isNotEmpty(split[105])){
            fcc.setBiangengmingcheng2(split[105]);
        }
        if(MyTools.isNotEmpty(split[106])){
            fcc.setBiangengdiyu2(split[106]);
        }
        if(MyTools.isNotEmpty(split[107])){
            fcc.setBiangengyewu2(split[107]);
        }
        if(MyTools.isNotEmpty(split[108])){
            fcc.setBiangengzhusuo2(split[108]);
        }
        if(MyTools.isNotEmpty(split[109])){
            fcc.setBiangengzijin2(split[109]);
        }
        if(MyTools.isNotEmpty(split[110])){
            fcc.setBiangengfaren2(split[110]);
        }
        if(MyTools.isNotEmpty(split[111])){
            fcc.setBianzhuguandanwei2(split[111]);
        }
        if(MyTools.isNotEmpty(split[112])){
            fcc.setFuzerenbiangeng2(split[112]);
        }
        if(MyTools.isNotEmpty(split[113])){
            fcc.setXiugaizhangcheng2(split[113]);
        }
        if(MyTools.isNotEmpty(split[114])){
            fcc.setDanganzhidu(split[114]);
        }
        if(MyTools.isNotEmpty(split[115])){
            fcc.setDanganbaoguandi(split[115]);
        }
        if(MyTools.isNotEmpty(split[116])){
            fcc.setXinchouguanlizhidu(split[116]);
        }
        if(MyTools.isNotEmpty(split[117])){
            fcc.setXinchouguanlizhidu2(split[117]);
        }
        if(MyTools.isNotEmpty(split[118])){
            fcc.setJiangchengzhidu(split[118]);
        }
        if(MyTools.isNotEmpty(split[119])){
            fcc.setYewupeixunzhidu(split[119]);
        }
        if(MyTools.isNotEmpty(split[120])){
            fcc.setCaiwuguanlizhidu(split[120]);
        }
        if(MyTools.isNotEmpty(split[121])){
            fcc.setGuziguanlizhidu(split[121]);
        }
        if(MyTools.isNotEmpty(split[122])){
            fcc.setZhixingkuaijizhidu(split[122]);
        }
        if(MyTools.isNotEmpty(split[123])){
            fcc.setQitapiaoju2(split[123]);
        }
        if(MyTools.isNotEmpty(split[124])){
            fcc.setPiaojuzhongleiqita2(split[124]);
        }
        if(MyTools.isNotEmpty(split[125])){
            fcc.setZhongyangdanwei(split[125]);
        }
        if(MyTools.isNotEmpty(split[126])){
            fcc.setFafangjiguan1(split[126]);
        }
        if(MyTools.isNotEmpty(split[127])){
            fcc.setFafangjiguan2(split[127]);
        }
        if(MyTools.isNotEmpty(split[128])){
            fcc.setFafangjiguan3(split[128]);
        }
        if(MyTools.isNotEmpty(split[129])){
            fcc.setFafangjiguan4(split[129]);
        }
        if(MyTools.isNotEmpty(split[130])){
            fcc.setFafangjiguan5(split[130]);
        }
        if(MyTools.isNotEmpty(split[131])){
            fcc.setFafangjiguan6(split[131]);
        }
        if(MyTools.isNotEmpty(split[132])){
            fcc.setFafangjiguan7(split[132]);
        }
        if(MyTools.isNotEmpty(split[133])){
            fcc.setRenminbikaihumingcheng(split[133]);
        }
        if(MyTools.isNotEmpty(split[134])){
            fcc.setWaibikaihumingcheng(split[134]);
        }
        if(MyTools.isNotEmpty(split[135])){
            fcc.setCaiwuhesuanshifouduli(split[135]);
        }
        if(MyTools.isNotEmpty(split[136])){
            fcc.setTjnjjieguo1(split[136]);
        }
        if(MyTools.isNotEmpty(split[137])){
            fcc.setTjnjjieguo2(split[137]);
        }
        if(MyTools.isNotEmpty(split[138])){
            fcc.setTjnjyijian1(split[138]);
        }
        if(MyTools.isNotEmpty(split[139])){
            fcc.setTjnjyijian2(split[139]);
        }
        if(MyTools.isNotEmpty(split[140])){
            fcc.setTjnjxingming1(split[140]);
        }
        if(MyTools.isNotEmpty(split[141])){
            fcc.setTjnjxingming2(split[141]);
        }
        if(MyTools.isNotEmpty(split[142])){
            fcc.setTjnjshijian1(DateUtils.strToDateLong(split[142]));
        }
        if(MyTools.isNotEmpty(split[143])){
            fcc.setTjnjshijian2(DateUtils.strToDateLong(split[143]));
        }
        if(MyTools.isNotEmpty(split[144])){
            fcc.setQitazhidu(split[144]);
        }
        if(MyTools.isNotEmpty(split[145])){
            fcc.setBiangenglishijianshi(split[145]);
        }
        if(MyTools.isNotEmpty(split[146])){
            fcc.setBiangenglishibanli(split[146]);
        }
        if(MyTools.isNotEmpty(split[147])){
            fcc.setBiangenglishishijian(DateUtils.strToDateLong(split[147]));
        }
        if(MyTools.isNotEmpty(split[148])){
            fcc.setZhuanzhigongzuorenshu(Integer.parseInt(split[148]));
        }
        if(MyTools.isNotEmpty(split[149])){
            fcc.setShifougongkai(split[149]);
        }
        if(MyTools.isNotEmpty(split[150])){
            fcc.setGuanfangwangzhan1(split[150]);
        }
        if(MyTools.isNotEmpty(split[151])){
            fcc.setWeixinpingtai1(split[151]);
        }
        if(MyTools.isNotEmpty(split[152])){
            fcc.setWeibo1(split[152]);
        }
        if(MyTools.isNotEmpty(split[153])){
            fcc.setZazhiqikan1(split[153]);
        }
        if(MyTools.isNotEmpty(split[154])){
            fcc.setQitafangshi1(split[154]);
        }
        if(MyTools.isNotEmpty(split[155])){
            fcc.setGuanfangwangzhan2(split[155]);
        }
        if(MyTools.isNotEmpty(split[156])){
            fcc.setWeixinpingtai2(split[156]);
        }
        if(MyTools.isNotEmpty(split[157])){
            fcc.setWeibo2(split[157]);
        }
        if(MyTools.isNotEmpty(split[158])){
            fcc.setZazhiqikan2(split[158]);
        }
        if(MyTools.isNotEmpty(split[159])){
            fcc.setHuiyuandahui(split[159]);
        }
        if(MyTools.isNotEmpty(split[160])){
            fcc.setGongzuoqqqun(split[160]);
        }
        if(MyTools.isNotEmpty(split[161])){
            fcc.setDuanxinpingtai(split[161]);
        }
        if(MyTools.isNotEmpty(split[162])){
            fcc.setQitafangshi2(split[162]);
        }
        if(MyTools.isNotEmpty(split[163])){
            fcc.setQitafangshi22(split[163]);
        }
        if(MyTools.isNotEmpty(split[164])){
            fcc.setQitafangshi11(split[164]);
        }

        return fcc;
    }
}

