package com.xgb.service;

import com.xgb.common.Utils;
import com.xgb.model.JjhnjReport4;
import com.xgb.util.DateUtils;
import com.xgb.util.MyTools;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
* @Auther: 
* @Date: 2019年12月24日 16:00:33
* @Description:
*/
public class ReadJjhnjReport4Service {

    public static JjhnjReport4 getContent(){
        List<JjhnjReport4> lists = new ArrayList<JjhnjReport4>();
        String path = Utils.getResourceBasePath() + "/xgb-data/data-api/config/JjhnjReport4.txt";
        File file = new File(path);
        JjhnjReport4  entity = null;
        Boolean boo = file.exists() && file.isFile();
        if(boo){
            BufferedReader bufferedReader = null;
            try {
                //构造一个BufferedReader类来读取文件
                bufferedReader = new BufferedReader(new FileReader(file));
                String linetxt = null;
                //result用来存储文件内容
                StringBuilder result = new StringBuilder();
                //按使用readLine方法，一次读一行
                while ((linetxt = bufferedReader.readLine()) != null) {
                    result.append(linetxt);
                }
                //输出读出的所有数据（StringBuilder类型）
                entity = getEntity(result.toString());
                lists.add(entity);
            } catch (Exception e) {
                System.out.println("读取文件内容出错");
                e.printStackTrace();
            } finally {
                try {
                    bufferedReader.close();
                } catch (IOException e1) {
                    e1.printStackTrace();
                }
            }
        }
        return entity;
    }
    public static JjhnjReport4 getEntity(String result){
        String[] split = result.split("\\|");
        JjhnjReport4 fcc = new JjhnjReport4();
        if(MyTools.isNotEmpty(split[0])){
            fcc.setId(Long.parseLong(split[0]));
        }
        if(MyTools.isNotEmpty(split[1])){
            fcc.setInstanceid(split[1]);
        }
        if(MyTools.isNotEmpty(split[2])){
            fcc.setOrganizationid(split[2]);
        }
        if(MyTools.isNotEmpty(split[3])){
            fcc.setStatus(Short.parseShort(split[3]));
        }
        if(MyTools.isNotEmpty(split[4])){
            fcc.setBianzhidanwei(split[4]);
        }
        if(MyTools.isNotEmpty(split[5])){
            fcc.setNiandu(split[5]);
        }
        if(MyTools.isNotEmpty(split[6])){
            fcc.setMojuanfeixian(Integer.parseInt(split[6]));
        }
        if(MyTools.isNotEmpty(split[7])){
            fcc.setMojuanxian(Integer.parseInt(split[7]));
        }
        if(MyTools.isNotEmpty(split[8])){
            fcc.setMojuanheji(Integer.parseInt(split[8]));
        }
        if(MyTools.isNotEmpty(split[9])){
            fcc.setLeijijuanfeixian(Integer.parseInt(split[9]));
        }
        if(MyTools.isNotEmpty(split[10])){
            fcc.setLeijijuanxian(Integer.parseInt(split[10]));
        }
        if(MyTools.isNotEmpty(split[11])){
            fcc.setLeijijuanheji(Integer.parseInt(split[11]));
        }
        if(MyTools.isNotEmpty(split[12])){
            fcc.setMohuifeixian(Integer.parseInt(split[12]));
        }
        if(MyTools.isNotEmpty(split[13])){
            fcc.setMohuixian(Integer.parseInt(split[13]));
        }
        if(MyTools.isNotEmpty(split[14])){
            fcc.setMohuiheji(Integer.parseInt(split[14]));
        }
        if(MyTools.isNotEmpty(split[15])){
            fcc.setLeijihuifeixian(Integer.parseInt(split[15]));
        }
        if(MyTools.isNotEmpty(split[16])){
            fcc.setLeijihuixian(Integer.parseInt(split[16]));
        }
        if(MyTools.isNotEmpty(split[17])){
            fcc.setLeijihuiheji(Integer.parseInt(split[17]));
        }
        if(MyTools.isNotEmpty(split[18])){
            fcc.setMofuwufeixian(Integer.parseInt(split[18]));
        }
        if(MyTools.isNotEmpty(split[19])){
            fcc.setMofuwuxian(Integer.parseInt(split[19]));
        }
        if(MyTools.isNotEmpty(split[20])){
            fcc.setMofuwuheji(Integer.parseInt(split[20]));
        }
        if(MyTools.isNotEmpty(split[21])){
            fcc.setLeijifuwufeixian(Integer.parseInt(split[21]));
        }
        if(MyTools.isNotEmpty(split[22])){
            fcc.setLeijifuwuxian(Integer.parseInt(split[22]));
        }
        if(MyTools.isNotEmpty(split[23])){
            fcc.setLeijifuwuheji(Integer.parseInt(split[23]));
        }
        if(MyTools.isNotEmpty(split[24])){
            fcc.setMoxiaoshoufeixian(Integer.parseInt(split[24]));
        }
        if(MyTools.isNotEmpty(split[25])){
            fcc.setMoxiaoshouxian(Integer.parseInt(split[25]));
        }
        if(MyTools.isNotEmpty(split[26])){
            fcc.setMoxiaoshouheji(Integer.parseInt(split[26]));
        }
        if(MyTools.isNotEmpty(split[27])){
            fcc.setLeijixiaoshoufeixian(Integer.parseInt(split[27]));
        }
        if(MyTools.isNotEmpty(split[28])){
            fcc.setLeijixiaoshouxian(Integer.parseInt(split[28]));
        }
        if(MyTools.isNotEmpty(split[29])){
            fcc.setLeijixiaoshouheji(Integer.parseInt(split[29]));
        }
        if(MyTools.isNotEmpty(split[30])){
            fcc.setMobuzhufeixian(Integer.parseInt(split[30]));
        }
        if(MyTools.isNotEmpty(split[31])){
            fcc.setMobuzhuxian(Integer.parseInt(split[31]));
        }
        if(MyTools.isNotEmpty(split[32])){
            fcc.setMobuzhuheji(Integer.parseInt(split[32]));
        }
        if(MyTools.isNotEmpty(split[33])){
            fcc.setLeijibuzhufeixian(Integer.parseInt(split[33]));
        }
        if(MyTools.isNotEmpty(split[34])){
            fcc.setMotouzifeixian(Integer.parseInt(split[34]));
        }
        if(MyTools.isNotEmpty(split[35])){
            fcc.setMotouzixian(Integer.parseInt(split[35]));
        }
        if(MyTools.isNotEmpty(split[36])){
            fcc.setMotouziheji(Integer.parseInt(split[36]));
        }
        if(MyTools.isNotEmpty(split[37])){
            fcc.setLeijitouzifeixian(Integer.parseInt(split[37]));
        }
        if(MyTools.isNotEmpty(split[38])){
            fcc.setLeijitouzixian(Integer.parseInt(split[38]));
        }
        if(MyTools.isNotEmpty(split[39])){
            fcc.setLeijitouziheji(Integer.parseInt(split[39]));
        }
        if(MyTools.isNotEmpty(split[40])){
            fcc.setMoqitafeixian(Integer.parseInt(split[40]));
        }
        if(MyTools.isNotEmpty(split[41])){
            fcc.setMoqitaxian(Integer.parseInt(split[41]));
        }
        if(MyTools.isNotEmpty(split[42])){
            fcc.setMoqitaheji(Integer.parseInt(split[42]));
        }
        if(MyTools.isNotEmpty(split[43])){
            fcc.setLeijiqitafeixian(Integer.parseInt(split[43]));
        }
        if(MyTools.isNotEmpty(split[44])){
            fcc.setLeijiqitaxian(Integer.parseInt(split[44]));
        }
        if(MyTools.isNotEmpty(split[45])){
            fcc.setLeijiqitaheji(Integer.parseInt(split[45]));
        }
        if(MyTools.isNotEmpty(split[46])){
            fcc.setMohejifeixian(Integer.parseInt(split[46]));
        }
        if(MyTools.isNotEmpty(split[47])){
            fcc.setMohejixian(Integer.parseInt(split[47]));
        }
        if(MyTools.isNotEmpty(split[48])){
            fcc.setMohejiheji(Integer.parseInt(split[48]));
        }
        if(MyTools.isNotEmpty(split[49])){
            fcc.setLeijihejifeixian(Integer.parseInt(split[49]));
        }
        if(MyTools.isNotEmpty(split[50])){
            fcc.setLeijihejixian(Integer.parseInt(split[50]));
        }
        if(MyTools.isNotEmpty(split[51])){
            fcc.setLeijihejiheji(Integer.parseInt(split[51]));
        }
        if(MyTools.isNotEmpty(split[52])){
            fcc.setMochengbenfeixian(Integer.parseInt(split[52]));
        }
        if(MyTools.isNotEmpty(split[53])){
            fcc.setMochengbenxian(Integer.parseInt(split[53]));
        }
        if(MyTools.isNotEmpty(split[54])){
            fcc.setMochengbenheji(Integer.parseInt(split[54]));
        }
        if(MyTools.isNotEmpty(split[55])){
            fcc.setLeijichengbenfeixian(Integer.parseInt(split[55]));
        }
        if(MyTools.isNotEmpty(split[56])){
            fcc.setLeijichengbenxian(Integer.parseInt(split[56]));
        }
        if(MyTools.isNotEmpty(split[57])){
            fcc.setLeijichengbenheji(Integer.parseInt(split[57]));
        }
        if(MyTools.isNotEmpty(split[58])){
            fcc.setMoqizhongfeixian1(Integer.parseInt(split[58]));
        }
        if(MyTools.isNotEmpty(split[59])){
            fcc.setMoqizhongxian1(Integer.parseInt(split[59]));
        }
        if(MyTools.isNotEmpty(split[60])){
            fcc.setMoqizhongheji1(Integer.parseInt(split[60]));
        }
        if(MyTools.isNotEmpty(split[61])){
            fcc.setLeijiqizhongfeixian1(Integer.parseInt(split[61]));
        }
        if(MyTools.isNotEmpty(split[62])){
            fcc.setLeijiqizhongxian1(Integer.parseInt(split[62]));
        }
        if(MyTools.isNotEmpty(split[63])){
            fcc.setLeijiqizhongheji1(Integer.parseInt(split[63]));
        }
        if(MyTools.isNotEmpty(split[64])){
            fcc.setMoqizhongfeixian2(Integer.parseInt(split[64]));
        }
        if(MyTools.isNotEmpty(split[65])){
            fcc.setMoqizhongxian2(Integer.parseInt(split[65]));
        }
        if(MyTools.isNotEmpty(split[66])){
            fcc.setMoqizhongheji2(Integer.parseInt(split[66]));
        }
        if(MyTools.isNotEmpty(split[67])){
            fcc.setLeijiqizhongfeixian2(Integer.parseInt(split[67]));
        }
        if(MyTools.isNotEmpty(split[68])){
            fcc.setLeijiqizhongxian2(Integer.parseInt(split[68]));
        }
        if(MyTools.isNotEmpty(split[69])){
            fcc.setLeijiqizhongheji2(Integer.parseInt(split[69]));
        }
        if(MyTools.isNotEmpty(split[70])){
            fcc.setMoqizhongfeixian3(Integer.parseInt(split[70]));
        }
        if(MyTools.isNotEmpty(split[71])){
            fcc.setMoqizhongxian3(Integer.parseInt(split[71]));
        }
        if(MyTools.isNotEmpty(split[72])){
            fcc.setMoqizhongheji3(Integer.parseInt(split[72]));
        }
        if(MyTools.isNotEmpty(split[73])){
            fcc.setLeijiqizhongfeixian3(Integer.parseInt(split[73]));
        }
        if(MyTools.isNotEmpty(split[74])){
            fcc.setLeijiqizhongxian3(Integer.parseInt(split[74]));
        }
        if(MyTools.isNotEmpty(split[75])){
            fcc.setLeijiqizhongheji3(Integer.parseInt(split[75]));
        }
        if(MyTools.isNotEmpty(split[76])){
            fcc.setMoqizhongfeixian4(Integer.parseInt(split[76]));
        }
        if(MyTools.isNotEmpty(split[77])){
            fcc.setMoqizhongxian4(Integer.parseInt(split[77]));
        }
        if(MyTools.isNotEmpty(split[78])){
            fcc.setMoqizhongheji4(Integer.parseInt(split[78]));
        }
        if(MyTools.isNotEmpty(split[79])){
            fcc.setLeijiqizhongfeixian4(Integer.parseInt(split[79]));
        }
        if(MyTools.isNotEmpty(split[80])){
            fcc.setLeijiqizhongxian4(Integer.parseInt(split[80]));
        }
        if(MyTools.isNotEmpty(split[81])){
            fcc.setLeijiqizhongheji4(Integer.parseInt(split[81]));
        }
        if(MyTools.isNotEmpty(split[82])){
            fcc.setMoguanlifeixian(Integer.parseInt(split[82]));
        }
        if(MyTools.isNotEmpty(split[83])){
            fcc.setMoguanlixian(Integer.parseInt(split[83]));
        }
        if(MyTools.isNotEmpty(split[84])){
            fcc.setMoguanliheji(Integer.parseInt(split[84]));
        }
        if(MyTools.isNotEmpty(split[85])){
            fcc.setLeijiguanlifeixian(Integer.parseInt(split[85]));
        }
        if(MyTools.isNotEmpty(split[86])){
            fcc.setLeijiguanlixian(Integer.parseInt(split[86]));
        }
        if(MyTools.isNotEmpty(split[87])){
            fcc.setLeijiguanliheji(Integer.parseInt(split[87]));
        }
        if(MyTools.isNotEmpty(split[88])){
            fcc.setMochouzifeixian(Integer.parseInt(split[88]));
        }
        if(MyTools.isNotEmpty(split[89])){
            fcc.setMochouzixian(Integer.parseInt(split[89]));
        }
        if(MyTools.isNotEmpty(split[90])){
            fcc.setMochouziheji(Integer.parseInt(split[90]));
        }
        if(MyTools.isNotEmpty(split[91])){
            fcc.setLeijichouzifeixian(Integer.parseInt(split[91]));
        }
        if(MyTools.isNotEmpty(split[92])){
            fcc.setLeijichouzixian(Integer.parseInt(split[92]));
        }
        if(MyTools.isNotEmpty(split[93])){
            fcc.setLeijichouziheji(Integer.parseInt(split[93]));
        }
        if(MyTools.isNotEmpty(split[94])){
            fcc.setMoqitafeiyongfei(Integer.parseInt(split[94]));
        }
        if(MyTools.isNotEmpty(split[95])){
            fcc.setMoqitafeiyongxian(Integer.parseInt(split[95]));
        }
        if(MyTools.isNotEmpty(split[96])){
            fcc.setMoqitafeiyongheji(Integer.parseInt(split[96]));
        }
        if(MyTools.isNotEmpty(split[97])){
            fcc.setLeijiqitafeiyongfeixian(Integer.parseInt(split[97]));
        }
        if(MyTools.isNotEmpty(split[98])){
            fcc.setLeijiqitafeiyongxian(Integer.parseInt(split[98]));
        }
        if(MyTools.isNotEmpty(split[99])){
            fcc.setLeijiqitafeiyongheji(Integer.parseInt(split[99]));
        }
        if(MyTools.isNotEmpty(split[100])){
            fcc.setMofeiyonghejifei(Integer.parseInt(split[100]));
        }
        if(MyTools.isNotEmpty(split[101])){
            fcc.setMofeiyonghejixian(Integer.parseInt(split[101]));
        }
        if(MyTools.isNotEmpty(split[102])){
            fcc.setMofeiyonghejiheji(Integer.parseInt(split[102]));
        }
        if(MyTools.isNotEmpty(split[103])){
            fcc.setLeijifeiyonghejifei(Integer.parseInt(split[103]));
        }
        if(MyTools.isNotEmpty(split[104])){
            fcc.setLeijifeiyonghejixian(Integer.parseInt(split[104]));
        }
        if(MyTools.isNotEmpty(split[105])){
            fcc.setLeijifeiyonghejiheji(Integer.parseInt(split[105]));
        }
        if(MyTools.isNotEmpty(split[106])){
            fcc.setMozhuanfeixian(Integer.parseInt(split[106]));
        }
        if(MyTools.isNotEmpty(split[107])){
            fcc.setMozhuanxian(Integer.parseInt(split[107]));
        }
        if(MyTools.isNotEmpty(split[108])){
            fcc.setMozhuanheji(Integer.parseInt(split[108]));
        }
        if(MyTools.isNotEmpty(split[109])){
            fcc.setLeijizhuanfeixian(Integer.parseInt(split[109]));
        }
        if(MyTools.isNotEmpty(split[110])){
            fcc.setLeijizhuanxian(Integer.parseInt(split[110]));
        }
        if(MyTools.isNotEmpty(split[111])){
            fcc.setLeijizhuanheji(Integer.parseInt(split[111]));
        }
        if(MyTools.isNotEmpty(split[112])){
            fcc.setMobiandongfeixian(Integer.parseInt(split[112]));
        }
        if(MyTools.isNotEmpty(split[113])){
            fcc.setMobiandongxian(Integer.parseInt(split[113]));
        }
        if(MyTools.isNotEmpty(split[114])){
            fcc.setMobiandongheji(Integer.parseInt(split[114]));
        }
        if(MyTools.isNotEmpty(split[115])){
            fcc.setLeijibiandongfeixian(Integer.parseInt(split[115]));
        }
        if(MyTools.isNotEmpty(split[116])){
            fcc.setLeijibiandongxian(Integer.parseInt(split[116]));
        }
        if(MyTools.isNotEmpty(split[117])){
            fcc.setLeijibiandongheji(Integer.parseInt(split[117]));
        }
        if(MyTools.isNotEmpty(split[118])){
            fcc.setLeijibuzhuxian(Integer.parseInt(split[118]));
        }
        if(MyTools.isNotEmpty(split[119])){
            fcc.setLeijibuzhuheji(Integer.parseInt(split[119]));
        }
        if(MyTools.isNotEmpty(split[120])){
            fcc.setQizhong1(split[120]);
        }
        if(MyTools.isNotEmpty(split[121])){
            fcc.setQizhong2(split[121]);
        }
        if(MyTools.isNotEmpty(split[122])){
            fcc.setQizhong3(split[122]);
        }
        if(MyTools.isNotEmpty(split[123])){
            fcc.setQizhong4(split[123]);
        }
        if(MyTools.isNotEmpty(split[124])){
            fcc.setMoqizhongfeixian5(Integer.parseInt(split[124]));
        }
        if(MyTools.isNotEmpty(split[125])){
            fcc.setMoqizhongfeixian6(Integer.parseInt(split[125]));
        }
        if(MyTools.isNotEmpty(split[126])){
            fcc.setMoqizhongfeixian7(Integer.parseInt(split[126]));
        }
        if(MyTools.isNotEmpty(split[127])){
            fcc.setMoqizhongfeixian8(Integer.parseInt(split[127]));
        }
        if(MyTools.isNotEmpty(split[128])){
            fcc.setMoqizhongxian5(Integer.parseInt(split[128]));
        }
        if(MyTools.isNotEmpty(split[129])){
            fcc.setMoqizhongxian6(Integer.parseInt(split[129]));
        }
        if(MyTools.isNotEmpty(split[130])){
            fcc.setMoqizhongxian7(Integer.parseInt(split[130]));
        }
        if(MyTools.isNotEmpty(split[131])){
            fcc.setMoqizhongxian8(Integer.parseInt(split[131]));
        }
        if(MyTools.isNotEmpty(split[132])){
            fcc.setMoqizhongheji5(Integer.parseInt(split[132]));
        }
        if(MyTools.isNotEmpty(split[133])){
            fcc.setMoqizhongheji6(Integer.parseInt(split[133]));
        }
        if(MyTools.isNotEmpty(split[134])){
            fcc.setMoqizhongheji7(Integer.parseInt(split[134]));
        }
        if(MyTools.isNotEmpty(split[135])){
            fcc.setMoqizhongheji8(Integer.parseInt(split[135]));
        }
        if(MyTools.isNotEmpty(split[136])){
            fcc.setLeijiqizhongfeixian5(Integer.parseInt(split[136]));
        }
        if(MyTools.isNotEmpty(split[137])){
            fcc.setLeijiqizhongfeixian6(Integer.parseInt(split[137]));
        }
        if(MyTools.isNotEmpty(split[138])){
            fcc.setLeijiqizhongfeixian7(Integer.parseInt(split[138]));
        }
        if(MyTools.isNotEmpty(split[139])){
            fcc.setLeijiqizhongfeixian8(Integer.parseInt(split[139]));
        }
        if(MyTools.isNotEmpty(split[140])){
            fcc.setLeijiqizhongxian5(Integer.parseInt(split[140]));
        }
        if(MyTools.isNotEmpty(split[141])){
            fcc.setLeijiqizhongxian6(Integer.parseInt(split[141]));
        }
        if(MyTools.isNotEmpty(split[142])){
            fcc.setLeijiqizhongxian7(Integer.parseInt(split[142]));
        }
        if(MyTools.isNotEmpty(split[143])){
            fcc.setLeijiqizhongxian8(Integer.parseInt(split[143]));
        }
        if(MyTools.isNotEmpty(split[144])){
            fcc.setLeijiqizhongheji5(Integer.parseInt(split[144]));
        }
        if(MyTools.isNotEmpty(split[145])){
            fcc.setLeijiqizhongheji6(Integer.parseInt(split[145]));
        }
        if(MyTools.isNotEmpty(split[146])){
            fcc.setLeijiqizhongheji7(Integer.parseInt(split[146]));
        }
        if(MyTools.isNotEmpty(split[147])){
            fcc.setLeijiqizhongheji8(Integer.parseInt(split[147]));
        }
        if(MyTools.isNotEmpty(split[148])){
            fcc.setRenyuan1(Integer.parseInt(split[148]));
        }
        if(MyTools.isNotEmpty(split[149])){
            fcc.setRenyuan2(Integer.parseInt(split[149]));
        }
        if(MyTools.isNotEmpty(split[150])){
            fcc.setRenyuan3(Integer.parseInt(split[150]));
        }
        if(MyTools.isNotEmpty(split[151])){
            fcc.setRenyuan4(Integer.parseInt(split[151]));
        }
        if(MyTools.isNotEmpty(split[152])){
            fcc.setRenyuan5(Integer.parseInt(split[152]));
        }
        if(MyTools.isNotEmpty(split[153])){
            fcc.setRenyuan6(Integer.parseInt(split[153]));
        }
        if(MyTools.isNotEmpty(split[154])){
            fcc.setRenyuan7(Integer.parseInt(split[154]));
        }
        if(MyTools.isNotEmpty(split[155])){
            fcc.setRichang1(Integer.parseInt(split[155]));
        }
        if(MyTools.isNotEmpty(split[156])){
            fcc.setRichang2(Integer.parseInt(split[156]));
        }
        if(MyTools.isNotEmpty(split[157])){
            fcc.setRichang3(Integer.parseInt(split[157]));
        }
        if(MyTools.isNotEmpty(split[158])){
            fcc.setRichang4(Integer.parseInt(split[158]));
        }
        if(MyTools.isNotEmpty(split[159])){
            fcc.setRichang5(Integer.parseInt(split[159]));
        }
        if(MyTools.isNotEmpty(split[160])){
            fcc.setRichang6(Integer.parseInt(split[160]));
        }
        if(MyTools.isNotEmpty(split[161])){
            fcc.setRichang7(Integer.parseInt(split[161]));
        }
        if(MyTools.isNotEmpty(split[162])){
            fcc.setGuding1(Integer.parseInt(split[162]));
        }
        if(MyTools.isNotEmpty(split[163])){
            fcc.setGuding2(Integer.parseInt(split[163]));
        }
        if(MyTools.isNotEmpty(split[164])){
            fcc.setGuding3(Integer.parseInt(split[164]));
        }
        if(MyTools.isNotEmpty(split[165])){
            fcc.setGuding4(Integer.parseInt(split[165]));
        }
        if(MyTools.isNotEmpty(split[166])){
            fcc.setGuding5(Integer.parseInt(split[166]));
        }
        if(MyTools.isNotEmpty(split[167])){
            fcc.setGuding6(Integer.parseInt(split[167]));
        }
        if(MyTools.isNotEmpty(split[168])){
            fcc.setGuding7(Integer.parseInt(split[168]));
        }
        if(MyTools.isNotEmpty(split[169])){
            fcc.setShuifei1(Integer.parseInt(split[169]));
        }
        if(MyTools.isNotEmpty(split[170])){
            fcc.setShuifei2(Integer.parseInt(split[170]));
        }
        if(MyTools.isNotEmpty(split[171])){
            fcc.setShuifei3(Integer.parseInt(split[171]));
        }
        if(MyTools.isNotEmpty(split[172])){
            fcc.setShuifei4(Integer.parseInt(split[172]));
        }
        if(MyTools.isNotEmpty(split[173])){
            fcc.setShuifei5(Integer.parseInt(split[173]));
        }
        if(MyTools.isNotEmpty(split[174])){
            fcc.setShuifei6(Integer.parseInt(split[174]));
        }
        if(MyTools.isNotEmpty(split[175])){
            fcc.setShuifei7(Integer.parseInt(split[175]));
        }
        if(MyTools.isNotEmpty(split[176])){
            fcc.setTjnjjieguo1(split[176]);
        }
        if(MyTools.isNotEmpty(split[177])){
            fcc.setTjnjjieguo2(split[177]);
        }
        if(MyTools.isNotEmpty(split[178])){
            fcc.setTjnjyijian1(split[178]);
        }
        if(MyTools.isNotEmpty(split[179])){
            fcc.setTjnjyijian2(split[179]);
        }
        if(MyTools.isNotEmpty(split[180])){
            fcc.setTjnjxingming1(split[180]);
        }
        if(MyTools.isNotEmpty(split[181])){
            fcc.setTjnjxingming2(split[181]);
        }
        if(MyTools.isNotEmpty(split[182])){
            fcc.setTjnjshijian1(DateUtils.strToDateLong(split[182]));
        }
        if(MyTools.isNotEmpty(split[183])){
            fcc.setTjnjshijian2(DateUtils.strToDateLong(split[183]));
        }
        if(MyTools.isNotEmpty(split[184])){
            fcc.setXianjinjuanzeng(Integer.parseInt(split[184]));
        }
        if(MyTools.isNotEmpty(split[185])){
            fcc.setXianjingongyi(Integer.parseInt(split[185]));
        }
        if(MyTools.isNotEmpty(split[186])){
            fcc.setXiandingxing(Integer.parseInt(split[186]));
        }
        if(MyTools.isNotEmpty(split[187])){
            fcc.setXiandingzichan(Integer.parseInt(split[187]));
        }
        if(MyTools.isNotEmpty(split[188])){
            fcc.setQita1(Integer.parseInt(split[188]));
        }
        if(MyTools.isNotEmpty(split[189])){
            fcc.setQita2(Integer.parseInt(split[189]));
        }
        if(MyTools.isNotEmpty(split[190])){
            fcc.setQita3(Integer.parseInt(split[190]));
        }
        if(MyTools.isNotEmpty(split[191])){
            fcc.setQita4(Integer.parseInt(split[191]));
        }
        if(MyTools.isNotEmpty(split[192])){
            fcc.setQita5(Integer.parseInt(split[192]));
        }
        if(MyTools.isNotEmpty(split[193])){
            fcc.setQita6(Integer.parseInt(split[193]));
        }
        if(MyTools.isNotEmpty(split[194])){
            fcc.setFujiafeixian(Integer.parseInt(split[194]));
        }
        if(MyTools.isNotEmpty(split[195])){
            fcc.setFujiaxian(Integer.parseInt(split[195]));
        }
        if(MyTools.isNotEmpty(split[196])){
            fcc.setFujiaheji(Integer.parseInt(split[196]));
        }
        if(MyTools.isNotEmpty(split[197])){
            fcc.setLeijifujiafeixian(Integer.parseInt(split[197]));
        }
        if(MyTools.isNotEmpty(split[198])){
            fcc.setLeijifujiaxian(Integer.parseInt(split[198]));
        }
        if(MyTools.isNotEmpty(split[199])){
            fcc.setLeijifujiaheji(Integer.parseInt(split[199]));
        }

        return fcc;
    }
}

