fdfs:
  soTimeout: 15000           # socket连接超时时长
  connectTimeout: 6000       # 连接tracker服务器超时时长
  thumbImage:                # 缩略图生成参数，可选
    width: 150
    height: 150
  resHost: 192.168.3.220      # nginx 浏览地址
  protocol: http            #协议
  storagePort: 801            # nginx 浏览端口
  trackerList:                # TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
  - 192.168.3.220:22122
  #- 192.168.1.102:22122
